project:
  type: website

website:
  title: "Aid Worker Security Analysis"
  navbar:
    logo: gtown.svg
    logo-link: https://www.georgetown.edu
    background: "#a02c2c"
    pinned: true
    right:
      - text: "Analytics"
        href: Analytics_Report.html
      - text: "Data Processing & EDA"
        href: D-Cleaning_and_EDA.html

format:
  html:
    theme: flatly
    page-layout: full
    css: styles.css
    code-fold: true
    toc: false
    embed-resources: true
    self-contained: true


filters:
  - quarto